import { StyleSheet } from 'react-native';

import { theme, typography } from '@/constants/theme';

export const dailyRoutineStyles = StyleSheet.create({
  screenRoot: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 24,
  },
  calendarSection: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 0,
    borderBottomWidth: 1,
    borderBottomColor: theme.cardBorder,
    backgroundColor: theme.cardBackground,
    shadowColor: theme.deepForest,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  calendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
    paddingHorizontal: 0,
  },
  calendarMonthRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minWidth: 0,
  },
  calendarIcon: {
    marginRight: 2,
  },
  calendarMonth: {
    fontFamily: typography.headingSemiBold,
    fontSize: 16,
    color: theme.text,
  },
  todayButton: {
    flexShrink: 0,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: theme.primary,
  },
  todayButtonText: {
    fontFamily: typography.bodyMedium,
    fontSize: 13,
    color: theme.white,
  },
  weekStripRow: {
    minHeight: 80,
  },
  weekStripScroll: {
    minHeight: 80,
  },
  weekStripContent: {
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 2,
    paddingHorizontal: 4,
  },
  weekChunk: {
    flexDirection: 'row',
    gap: 6,
  },
  dayCell: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 2,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.cardBorder,
    backgroundColor: theme.backgroundSecondary,
  },
  dayCellSelected: {
    borderColor: theme.primary,
    backgroundColor: theme.mintGlow,
    borderWidth: 2,
  },
  dayCellToday: {
    borderColor: theme.primary,
    backgroundColor: theme.mintGlow,
  },
  dayCellTodaySelected: {
    borderColor: theme.primary,
    backgroundColor: theme.primary,
  },
  dayCellTodaySelectedText: {
    color: theme.white,
  },
  todayDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: theme.primary,
    marginTop: 3,
  },
  dayNumber: {
    fontFamily: typography.headingSemiBold,
    fontSize: 15,
    color: theme.text,
  },
  dayLabel: {
    fontFamily: typography.body,
    fontSize: 10,
    color: theme.textSecondary,
    marginTop: 1,
    textTransform: 'uppercase',
  },
  timelineContainer: {
    flex: 1,
    paddingHorizontal: 0,
    paddingTop: 0,
    position: 'relative',
    minHeight: 0,
  },
  emptyStateWrapper: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 48,
  },
  timelineScrollView: {
    flex: 1,
    minHeight: 0,
  },
  timelineScrollContent: {
    paddingBottom: 96,
  },
  header: {
    marginBottom: 12,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  headerDateBlock: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
  },
  headerDate: {
    fontFamily: typography.body,
    fontSize: 12,
    color: theme.textSecondary,
    letterSpacing: 1,
  },
  headerDateNum: {
    fontFamily: typography.headingSemiBold,
    fontSize: 28,
    color: theme.heading,
  },
  headerTitle: {
    fontFamily: typography.heading,
    fontSize: 24,
    color: theme.heading,
  },
  headerSubtitle: {
    fontFamily: typography.body,
    fontSize: 14,
    color: theme.textSecondary,
    marginTop: 4,
  },
  segmentTabs: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 12,
    paddingHorizontal: 8,
  },
  segmentPill: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: theme.backgroundSecondary,
    borderWidth: 1,
    borderColor: theme.cardBorder,
  },
  segmentPillActive: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  segmentPillText: {
    fontFamily: typography.bodyMedium,
    fontSize: 13,
    color: theme.textSecondary,
  },
  segmentPillTextActive: {
    color: theme.white,
  },
  clockSection: {
    alignItems: 'center',
    paddingTop: 8,
    paddingBottom: 8,
    position: 'relative',
  },
  clockHorizontalScroll: {
    width: '100%',
  },
  clockHorizontalContent: {
    flexDirection: 'row',
  },
  clockPage: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  clockWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    width: '100%',
  },
  clockChart: {
    alignSelf: 'center',
  },
  // Timeline (vertical day schedule)
  timelineSection: {
    paddingTop: 8,
    paddingBottom: 24,
    position: 'relative',
  },
  quickHighlightsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    gap: 16,
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  quickHighlightItem: {
    alignItems: 'center',
    minWidth: 64,
  },
  quickHighlightCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  quickHighlightLabel: {
    fontFamily: typography.body,
    fontSize: 11,
    color: theme.textSecondary,
    textAlign: 'center',
    maxWidth: 72,
  },
  timelineList: {
    paddingBottom: 80,
  },
  eventGroupContainer: {
    flex: 1,
    minWidth: 0,
  },
  timelineRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 4,
    minHeight: 56,
  },
  timeColumn: {
    width: 48,
    paddingTop: 2,
    paddingRight: 8,
  },
  timeMarker: {
    fontFamily: typography.bodyMedium,
    fontSize: 12,
    color: theme.text,
  },
  timelineContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 52,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: theme.cardBorder,
  },
  eventBar: {
    width: 4,
    alignSelf: 'stretch',
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
  },
  eventBlock: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 10,
  },
  eventIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventBlockText: {
    flex: 1,
  },
  eventBlockTitle: {
    fontFamily: typography.headingSemiBold,
    fontSize: 15,
    color: theme.text,
  },
  eventBlockTime: {
    fontFamily: typography.body,
    fontSize: 12,
    color: theme.text,
    marginTop: 2,
  },
  eventCompletionCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventCompletionCircleDone: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  eventCompletionCirclePending: {
    borderColor: theme.cardBorder,
    backgroundColor: theme.cardBackground,
  },
  eventDeleteButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.backgroundSecondary,
  },
  timelineSwipeWrapper: {
    flex: 1,
    minWidth: 0,
  },
  swipeDeleteAction: {
    backgroundColor: theme.appBarNotificationBadge,
    justifyContent: 'center',
    alignItems: 'center',
    width: 80,
    minHeight: 52,
    borderRadius: 12,
    marginRight: 4,
  },
  intervalRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 44,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: theme.cardBorder,
    backgroundColor: theme.backgroundSecondary,
  },
  intervalText: {
    fontFamily: typography.body,
    fontSize: 13,
    color: theme.textSecondary,
  },
  fab: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: theme.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: theme.deepForest,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  rangeHint: {
    fontFamily: typography.body,
    fontSize: 13,
    color: theme.textSecondary,
    textAlign: 'center',
    marginTop: 12,
  },
  legend: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
    marginTop: 16,
    paddingHorizontal: 8,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: theme.cardBackground,
    borderWidth: 1,
    borderColor: theme.cardBorder,
    maxWidth: '48%',
  },
  legendCheckbox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  legendCheckboxCompleted: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  legendCheckboxPending: {
    borderColor: theme.cardBorder,
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  legendText: {
    flex: 1,
    fontFamily: typography.body,
    fontSize: 12,
    color: theme.text,
  },
  legendTextCompleted: {
    textDecorationLine: 'line-through',
    color: theme.textSecondary,
  },
  createEventButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.cardBorder,
    backgroundColor: theme.backgroundSecondary,
    marginTop: 16,
    gap: 8,
  },
  createEventButtonText: {
    fontFamily: typography.bodyMedium,
    fontSize: 15,
    color: theme.primary,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 24,
  },
  emptyIcon: {
    marginBottom: 16,
  },
  emptyTitle: {
    fontFamily: typography.headingSemiBold,
    fontSize: 18,
    color: theme.text,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontFamily: typography.body,
    fontSize: 14,
    color: theme.textSecondary,
    textAlign: 'center',
    marginTop: 8,
  },
  endOfDay: {
    fontFamily: typography.body,
    fontSize: 13,
    color: theme.textSecondary,
    marginTop: 16,
  },
});
