import { StyleSheet } from 'react-native';

import { theme, typography } from '@/constants/theme';

export const createRoutineEventSheetStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  container: {
    backgroundColor: theme.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingHorizontal: 24,
    paddingBottom: 32,
    maxHeight: '85%',
  },
  contentScroll: {
    maxHeight: 480,
  },
  contentScrollContent: {
    paddingBottom: 16,
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: theme.cardBorder,
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 16,
  },
  title: {
    fontFamily: typography.heading,
    fontSize: 20,
    color: theme.text,
    marginBottom: 20,
  },
  inputLabel: {
    fontFamily: typography.bodyMedium,
    fontSize: 14,
    color: theme.text,
    marginBottom: 8,
  },
  input: {
    fontFamily: typography.body,
    fontSize: 16,
    color: theme.text,
    backgroundColor: theme.backgroundSecondary,
    borderWidth: 1,
    borderColor: theme.cardBorder,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 16,
  },
  timeRow: {
    flexDirection: 'row',
    gap: 16,
  },
  timeInputGroup: {
    flex: 1,
  },
  sectionLabel: {
    fontFamily: typography.bodyMedium,
    fontSize: 14,
    color: theme.text,
    marginBottom: 10,
    marginTop: 8,
  },
  iconScroll: {
    marginHorizontal: -24,
    marginBottom: 8,
  },
  iconScrollContent: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 24,
    paddingBottom: 8,
  },
  iconOption: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: theme.backgroundSecondary,
    borderWidth: 2,
    borderColor: theme.cardBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconOptionSelected: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  colorRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  colorOption: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  colorOptionSelected: {
    borderColor: theme.text,
    borderWidth: 3,
  },
  reminderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: theme.backgroundSecondary,
    borderRadius: 12,
    marginBottom: 8,
  },
  reminderLabel: {
    fontFamily: typography.body,
    fontSize: 15,
    color: theme.text,
  },
  toggle: {
    width: 50,
    height: 28,
    borderRadius: 14,
    backgroundColor: theme.cardBorder,
    padding: 2,
    justifyContent: 'center',
  },
  toggleOn: {
    backgroundColor: theme.primary,
  },
  toggleThumb: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.white,
    alignSelf: 'flex-start',
  },
  toggleThumbOn: {
    alignSelf: 'flex-end',
  },
  reminderOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  reminderChip: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: theme.backgroundSecondary,
    borderWidth: 1,
    borderColor: theme.cardBorder,
  },
  reminderChipSelected: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  reminderChipText: {
    fontFamily: typography.body,
    fontSize: 13,
    color: theme.text,
  },
  reminderChipTextSelected: {
    color: theme.white,
  },
  customReminderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexBasis: '100%',
    marginTop: 4,
  },
  customReminderLabel: {
    fontFamily: typography.body,
    fontSize: 13,
    color: theme.textSecondary,
  },
  customReminderInput: {
    fontFamily: typography.body,
    fontSize: 16,
    color: theme.text,
    backgroundColor: theme.backgroundSecondary,
    borderWidth: 1,
    borderColor: theme.cardBorder,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    minWidth: 60,
  },
  buttonsRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 24,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: theme.backgroundSecondary,
    borderWidth: 1,
    borderColor: theme.cardBorder,
  },
  cancelButtonText: {
    fontFamily: typography.bodyMedium,
    fontSize: 15,
    color: theme.text,
  },
  saveButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: theme.primary,
  },
  saveButtonDisabled: {
    opacity: 0.5,
  },
  saveButtonText: {
    fontFamily: typography.bodyMedium,
    fontSize: 15,
    color: theme.white,
  },
});
