import { StyleSheet } from 'react-native';

import { theme, typography } from '@/constants/theme';

export const routineDayViewStyles = StyleSheet.create({
  card: {
    flex: 1,
    marginHorizontal: 0,
    marginTop: 0,
    marginBottom: 16,
    borderRadius: 24,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: theme.cardBorder,
    backgroundColor: theme.cardBackground,
    shadowColor: theme.deepForest,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 3,
  },
  arcHeader: {
    width: '100%',
    height: 100,
    overflow: 'hidden',
    position: 'relative',
  },
  arcGradient: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  arcLabelSunrise: {
    position: 'absolute',
    top: 6,
    left: 16,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  arcLabelSunset: {
    position: 'absolute',
    top: 10,
    right: 16,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  arcLabelText: {
    fontFamily: typography.bodyMedium,
    fontSize: 10,
    color: theme.text,
  },
  arcSvgWrapper: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 44,
  },
  sliderContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 44,
    paddingHorizontal: 24,
    justifyContent: 'center',
  },
  sliderTrack: {
    position: 'absolute',
    bottom: 20,
    left: 24,
    right: 24,
    height: 4,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  sliderProgress: {
    height: '100%',
    borderRadius: 8,
    overflow: 'hidden',
  },
  sliderThumb: {
    position: 'absolute',
    bottom: 14,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: theme.white,
    borderWidth: 2,
    borderColor: theme.primary,
    shadowColor: theme.deepForest,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  sliderTooltip: {
    position: 'absolute',
    backgroundColor: theme.deepForest,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    minWidth: 48,
    alignItems: 'center',
    transform: [{ translateX: -24 }],
  },
  sliderTooltipText: {
    fontFamily: typography.bodyMedium,
    fontSize: 12,
    color: theme.white,
  },
  sliderMarkers: {
    position: 'absolute',
    bottom: 2,
    left: 24,
    right: 24,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sliderMarkerText: {
    fontFamily: typography.body,
    fontSize: 9,
    color: theme.textSecondary,
  },
  timelineWrapper: {
    flex: 1,
    minHeight: 0,
    position: 'relative',
  },
  timelineScrollView: {
    flex: 1,
    minHeight: 0,
    backgroundColor: 'transparent',
  },
  contentArea: {
    paddingHorizontal: 12,
    paddingTop: 16,
    paddingBottom: 96,
    minHeight: 0,
  },
  timelineWithRuler: {
    flexDirection: 'row',
    flex: 1,
  },
  timeRulerColumn: {
    width: 48,
    paddingRight: 12,
    flexDirection: 'column',
  },
  timeRulerLabel: {
    fontFamily: typography.bodyMedium,
    fontSize: 12,
    color: theme.textSecondary,
  },
  timeRulerLabelTouchable: {
    position: 'absolute',
    left: 0,
    right: 0,
    paddingVertical: 8,
    paddingRight: 12,
    minHeight: 32,
    justifyContent: 'center',
  },
  currentTimeLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: theme.appBarNotificationBadge,
    zIndex: 10,
  },
  selectionOverlay: {
    position: 'absolute',
    left: 48,
    right: 0,
    backgroundColor: 'rgba(136, 181, 98, 0.25)',
    borderWidth: 2,
    borderColor: theme.primary,
    borderRadius: 8,
    zIndex: 5,
  },
  timelineList: {
    flex: 1,
    paddingBottom: 24,
    minWidth: 0,
  },
  timelineRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginBottom: 8,
  },
  timelineRowHighlight: {
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    borderRadius: 12,
    marginHorizontal: -4,
    paddingHorizontal: 4,
  },
  eventTile: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 48,
    alignSelf: 'stretch',
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: theme.cardBorder,
    backgroundColor: theme.cardBackground,
  },
  eventBar: {
    width: 3,
    alignSelf: 'stretch',
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
  },
  eventBlock: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 10,
  },
  eventIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventBlockText: {
    flex: 1,
    minWidth: 0,
  },
  eventBlockTitle: {
    fontFamily: typography.headingSemiBold,
    fontSize: 15,
    color: theme.text,
  },
  eventBlockTime: {
    fontFamily: typography.body,
    fontSize: 12,
    color: theme.textSecondary,
    marginTop: 2,
  },
  eventCompletionCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventCompletionCircleDone: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  eventCompletionCirclePending: {
    borderColor: theme.cardBorder,
    backgroundColor: theme.cardBackground,
  },
  gapRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 44,
    alignSelf: 'stretch',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: theme.cardBorder,
    backgroundColor: theme.backgroundSecondary,
    gap: 8,
  },
  gapIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.mintGlow,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gapText: {
    fontFamily: typography.body,
    fontSize: 13,
    color: theme.textSecondary,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 40,
    paddingHorizontal: 24,
  },
  emptyIcon: {
    marginBottom: 16,
  },
  emptyTitle: {
    fontFamily: typography.headingSemiBold,
    fontSize: 18,
    color: theme.text,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontFamily: typography.body,
    fontSize: 14,
    color: theme.textSecondary,
    textAlign: 'center',
    marginTop: 8,
  },
  endOfDay: {
    fontFamily: typography.body,
    fontSize: 13,
    color: theme.textSecondary,
    marginTop: 16,
  },
});
